version: '3'
services:
  jenkins:
    container_name: jenkins
    image: jenkins/jenkins
    ports:
        - "8081:8080"
    volumes:
        - "$PWD/jenkinshome:/var/jenkinshome"
    networks:
        - net
networks:
  net:
